# Generated by Django 5.0.6 on 2024-07-07 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_transactionmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='bonus_balance',
            field=models.FloatField(default=0.0),
        ),
    ]
